# Generated by Django 2.1.7 on 2019-05-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190526_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='project_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasktracker_project.Project'),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='team_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasktracker_team.Team'),
        ),
    ]
