# Generated by Django 2.1.7 on 2019-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_task', '0002_auto_20190428_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='entry_date',
            field=models.DateField(null=True),
        ),
    ]
