# Generated by Django 2.1.7 on 2019-05-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_task', '0004_auto_20190509_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
