# Generated by Django 2.1.7 on 2019-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notes', '0002_notes_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
