# Generated by Django 2.1.7 on 2019-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasktracker_team', '0001_initial'),
        ('tasktracker_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='tasktracker_team.Team'),
        ),
    ]
