# Generated by Django 2.1.7 on 2019-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_project', '0003_auto_20190428_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
