# Generated by Django 2.1.7 on 2019-05-25 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_project', '0004_projectmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='user_id',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
