# Generated by Django 2.1.7 on 2019-05-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_project', '0005_auto_20190525_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
