# Generated by Django 2.1.7 on 2019-05-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_team', '0004_teammember_role'),
        ('tasktracker_project', '0006_auto_20190526_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker_project.Project')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker_team.Team')),
            ],
        ),
    ]
