# Generated by Django 2.1.7 on 2019-05-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker_team', '0003_teamnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
